stages:
  - deploy
variables:
  GITHUB_REPO: "LifeVerse-Development/Website"
  GIT_AUTHOR_NAME: "LifeVerse-Development"
  GIT_AUTHOR_EMAIL: "lifeversegame@gmail.com"
  GIT_COMMITTER_NAME: "GitLab CI/CD"
  GIT_COMMITTER_EMAIL: "gitlab-ci@example.com"
deploy_to_github:
  stage: deploy
  script:
    - echo "Starte Deployment nach GitHub..."
    - git config --global user.name "$GIT_AUTHOR_NAME"
    - git config --global user.email "$GIT_AUTHOR_EMAIL"
    - git clone https://oauth2:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git temp-repo
    - cd temp-repo
    - git remote add gitlab-origin $CI_REPOSITORY_URL
    - git fetch gitlab-origin --tags
    - git push https://oauth2:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git
    - cd ..
    - rm -rf temp-repo
  only:
    - main